version: 0.2
phases:
  install:
    runtime-versions:
      # https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/available-runtimes.html
      nodejs: 12
    commands:
      - echo install started on `date`
      - node -e "console.log('Running Node.js ' + process.version)"
      - cd nextjs_sample
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run next export
  post_build:
    commands:
      - ls
#      - aws s3 sync ./build s3://### --delete --acl public-read 
#      - aws cloudfront create-invalidation --distribution-id ###ID### --paths "/*"
