version: 0.2
phases:
  install:
    commands:
      - echo install started on `date`
      - npm install next react react-dom
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install node
      - node -e "console.log('Running Node.js ' + process.version)"
  build:
    commands:
      - echo Build started on `date`
      - cd nextjs_sample
      - npm next export
  post_build:
    commands:
      - ls
#      - aws s3 sync ./build s3://### --delete --acl public-read 
#      - aws cloudfront create-invalidation --distribution-id ###ID### --paths "/*"
